export const DAY_LOADING = 'DAY_LOADING';
export const DAY_FAILED = 'DAY_FAILED';
export const ADD_DAY = 'ADD_DAY';
export const MOVIE_LOADING = 'MOVIE_LOADING';
export const MOVIE_FAILED = 'MOVIE_FAILED';
export const ADD_MOVIE = 'ADD_MOVIE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
